### PR TITLE
Store the config in a module rather than a global constant

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by cbeer** [comment]
Is there anything we need to do to preserve backwards compatibility? I'm not sure what the downstream expectations are..

**Comment by jcoyne** [comment]
I don't think so, this is all internal.  Plus VERSION < 1.0

**Comment by barmintor** [comment]
if the use of that config is local to Qa::Authorities::LocalSubauthority, is there a reason not to attach it there?

**Comment by cbeer** [comment]
Rebase (now that `Qa::Authorities::LocalSubauthority` is removed..)?

**Comment by barmintor** [comment]
Rebased.

**Pull request merged**
