### PR TITLE
Add search method to see if wants the controller with the request.

### PR DESCRIPTION
**Pull request by andjsmit**
Needed for a local QA that uses a SearchBuilder.

### CODE REVIEW

**Comment by jcoyne** [comment]
Can you please add a test?

**Comment by andjsmit** [comment]
@jcoyne I'm stuck on how to test this as no included authorities would require two arguments for its search method. Not sure how to go about mocking an authority if that is what is needed. Could you give me a clue on how to get started. Thanks.

**Comment by jcoyne** [comment]
You can define an authority class  that takes two args in the test.

**Comment by jcoyne** [comment]
This looks good @andjsmit. Can you squash these commits?

**Comment by andjsmit** [comment]
@jcoyne Squashed it. Thanks.

**Pull request merged**
