### PR TITLE
Make local tables generator point at the namespaced table for local authorities

### LINKED ISSUE #130: Table generator does invalid substitution.
I see this generated in the `CreateQaLocalAuthorityEntries` migration:
`      t.references :local_authority, foreign_key: true`

but this is the first argument of the gsub in the tables_generator:
 `'t.references :local_authority, index: true, foreign_key: true'`

I don't know why it's trying to match that `index: true`. Perhaps that's a rails 4 thing or a mysql only thing, but we should see if we can do the substitution in a way that matches all cases.

Reported by @acozine

### PR DESCRIPTION
**Pull request by mjgiarlo**
Fixes #130

Supersedes #139.

### CODE REVIEW

**Comment by mjgiarlo** [comment]
@revgum Can you point an installation at this branch to see if it fixes the problem you're seeing?

**Comment by jcoyne** [comment]
@mjgiarlo in the future can you keep the rubocop stuff in a separate commit so we can see where the real changes are?

**Comment by jcoyne** [comment]
@mjgiarlo rubocop still has issues.

**Comment by mjgiarlo** [comment]
Rubocop is being weird -- showing me errors on Travis that I don't see locally. Ideally these would not be part of this branch.

**Comment by mjgiarlo** [comment]
@jcoyne I can't get this rubocop violation to trigger locally. Not sure wtf is going on.

**Comment by mjgiarlo** [comment]
@jcoyne OK, this is :green_heart:, finally. I'd like @revgum to confirm this fixes what he was seeing before we merge this, though.

**Comment by mjgiarlo** [comment]
@revgum says it works. Merging.

**Pull request merged**
